// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0X_1d-Qw3uajxjb3Iei4c9XTZbeg5Ogw',
    appId: '1:616331963382:web:a04ddf0ce22e3d242935d7',
    messagingSenderId: '616331963382',
    projectId: 'tchakolo',
    authDomain: 'tchakolo.firebaseapp.com',
    storageBucket: 'tchakolo.appspot.com',
    measurementId: 'G-18VMGSHFLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHsahqgrvszsOFzI3BFRp6sMB261LKDQ',
    appId: '1:616331963382:android:0422cce83a14403f2935d7',
    messagingSenderId: '616331963382',
    projectId: 'tchakolo',
    storageBucket: 'tchakolo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsFk90zdcN9N7OzQ4UAVdGAkufGFTGl6Q',
    appId: '1:616331963382:ios:6ddf58439c91da2f2935d7',
    messagingSenderId: '616331963382',
    projectId: 'tchakolo',
    storageBucket: 'tchakolo.appspot.com',
    iosClientId: '616331963382-g026p1lrqclav5cqg6eue0ddratf4lqo.apps.googleusercontent.com',
    iosBundleId: 'cm.tchakolo.app',
  );
}
